server:
  port: 9094

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: ORDER-SERVICE
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/
      host: localhost
      port: 27017
      username: admin
      password: admin
      database: order_db
      repositories:
        enabled: true
